### ISSUE TITLE
【UI组件】颜色选择器缺失

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Blazor#138] opened 2021-12-17 05:58 UTC
![颜色选择器缺失](https://user-images.githubusercontent.com/95004531/146496673-79bfe0dc-a5b5-4556-aa41-ddf91657fc61.png)

**Comment by wangzengxing** [comment] 2022-02-23 09:29
ColorPicker is not completed and should be finished in 0.4.0.So we move this issue to 0.4.0 milestone.

**Comment by capdiem** [comment] 2023-10-19 07:28
duplicate of #1546

**Closed by capdiem** 2023-10-19 07:28 UTC
Labels: type/enhancement
