### ISSUE TITLE
【UI组件】Chip--选中的效果图和代码缺失

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Blazor#57] opened 2021-12-16 09:02 UTC
如题
![企业微信截图_16385035176697](https://user-images.githubusercontent.com/95004531/146342342-11f1d716-d8bf-43c5-bc79-805107ac64e2.png)

**Comment by wangzengxing** [comment] 2022-02-22 06:45
Since no  combobox component yet, we move this to 0.4.0 milestone.

**Comment by doddgu** [comment] 2022-10-19 03:05
#102

**Comment by capdiem** [comment] 2024-05-27 01:35
Duplicate of #116

**Closed by capdiem** 2024-05-27 01:35 UTC
Labels: type/bug, type/documentation
