### ISSUE TITLE
Add support to enter and save Optional Values in AutoComplete component 

### ISSUE THREAD

**Issue by hamiddd1980** [masastack/MASA.Blazor#585] opened 2022-07-23 19:16 UTC
**Is your feature request related to a problem? Please describe.**
in **MAutocomplete** component with defined **Items and bind-Value**, when the entered text doesn't match any items in Dropdown Items (the Text isn't in Items), then there is no way to capture entered **Text** and save it to Bound field.
for example you type **"apple**" and want to save it(**apple**). because the filtered dropdown items doesn't contain **apple** word,you can not save(capture) **apple**.

**Describe the solution you'd like**
Add a feature and property to **MAutocomplete** to make it possible to save(capture) an entered text that is not in the **Items (dropdown list)**. like **ForceTextToValue**:
```
<MAutocomplete ForceTextToValue="true"
                              @bind-Value="_values"
                               Items="_items"
                               ItemText="r=>r"
                               ItemValue="r=>r"
</MAutocomplete>
```

**Describe alternatives you've considered**

**Additional context**

**Comment by doddgu** [comment] 2022-07-25 08:49
I think you need a new component `MComboBox`, it can add new items if it doesn't exists.

**Comment by capdiem** [comment] 2024-06-05 01:42
Duplicate of #102

**Closed by capdiem** 2024-06-05 01:42 UTC
Labels: type/enhancement
