### ISSUE TITLE
File inputs . Unable to upload file

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Blazor#695] opened 2022-10-11 08:00 UTC
Server : 移动端
无法上传文件，点击输入框无反应
![b9c49ccd-3b99-4bb4-9cca-2b415840d950](https://user-images.githubusercontent.com/95004531/195031445-66627cb1-1de9-4869-a0e8-bf05569a500b.jpg)

**Comment by capdiem** [comment] 2024-06-05 01:52
Duplicate of #564

**Closed by capdiem** 2024-06-05 01:52 UTC
Labels: type/bug, mobile, hosted/server, component/File inputs
